server:
  servlet:
    context-path: /newcoder


spring:
  thymeleaf:
    cache: false
  datasource:
    username: root
    password: kinnon.553
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/newcoder?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
  mail:
    host: smtp.qq.com
    username: 741551902@qq.com
    password: flqbiqlkrojibchj

  quartz:
    job-store-type: jdbc
    properties:
      org:
        quartz:
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            isClustered: true
          scheduler:
            instanceId: AUTO
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 5
    scheduler-name: communityScheduler



  redis:
    host: localhost
    database: 11

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: newcoder-consumer-group
      enable-auto-commit: true
      auto-commit-interval: 3000
#  data:

  elasticsearch:
    rest:
      uris: localhost:9200
    cluster:
      name: newcoder

  #ExcutorTask
  task:
    execution:
      pool:
        max-size: 15
        queue-capacity: 100
        core-size: 5
    scheduling:
      pool:
        size: 5
  #TaskScheduleExcutor

mybatis-plus:
  type-aliases-package: com.kinnon.domain
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    log-impl: org.apache.ibatis.logging.slf4j.Slf4jLoggerImpl
logging:
  level:
    root: info


newcoder:
  path:
    domain: "http://localhost:8080"
    upload: d://work/data/upload

qiniu:
  key:
    access: wFhvmXLCXA4XTKzDbbVzOCRNtghC8fsfg_UgKzJB
    secret: KMPpxx0Xe4nmz3XctKGqAMy-VnE5wM0j2zaJ69uL
  bucket:
    header:
      name: newcoder2022
      url : http://ri5221mgj.hn-bkt.clouddn.com

#caffeine
caffeine:
  posts:
    max-size: 15
    expire-seconds: 180









