server:
  servlet:
    context-path: /newcoder


spring:
  thymeleaf:
    cache: false
  datasource:
    username: root
    password: kinnon.553
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/newcoder?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
  mail:
    host: smtp.qq.com
    username: 627074396@qq.com
    password: siyccpdhabvqbfje




mybatis-plus:
  type-aliases-package: com.kinnon.domain
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    log-impl: org.apache.ibatis.logging.slf4j.Slf4jLoggerImpl
logging:
  level:
    root: info


newcoder:
  path:
    domain: "http://localhost:8080"

